import 'package:flutter/material.dart';

class AppColorSchemes {
  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff000000),
      surfaceTint: Color(0xff595E6C),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff262626),
      onPrimaryContainer: Color(0xffb3b1b0),
      secondary: Color(0xff0ea5e9),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff2db1f6),
      onSecondaryContainer: Color(0xff002a3f),
      tertiary: Color(0xff516072),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff272525),
      onTertiaryContainer: Color(0xffb4b0b0),
      error: Color(0xff97000a),
      onError: Color(0xffffffff),
      errorContainer: Color.fromARGB(255, 199, 136, 134),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfff8fafc),
      onSurface: Color(0xff1c1b1b),
      onSurfaceVariant: Color(0xff44474c),
      outline: Color(0xff747878),
      outlineVariant: Color(0xffc4c7c7),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff313030),
      inversePrimary: Color(0xffc8c6c5),
      primaryFixed: Color(0xffe5e2e1),
      onPrimaryFixed: Color(0xff161c28),
      primaryFixedDim: Color(0xffC1C6D7),
      onPrimaryFixedVariant: Color(0xff414754),
      secondaryFixed: Color(0xffc9e6ff),
      onSecondaryFixed: Color(0xff001e2f),
      secondaryFixedDim: Color(0xff89ceff),
      onSecondaryFixedVariant: Color(0xff004c6e),
      tertiaryFixed: Color(0xffe6e1e1),
      onTertiaryFixed: Color(0xff1c1b1b),
      tertiaryFixedDim: Color(0xffcac5c5),
      onTertiaryFixedVariant: Color(0xff484646),
      surfaceDim: Color(0xffddd9d8),
      surfaceBright: Color(0xfffdf8f8),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff7f3f2),
      surfaceContainer: Color(0xfff1edec),
      surfaceContainerHigh: Color(0xffebe7e6),
      surfaceContainerHighest: Color(0xffe5e2e1),
    );
  }
}
